project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left: 
      - text: Exercises
        menu: 
          - text: Hands-on Exercise 1
            href: Hands-on_Ex1.qmd
          - text: In-class Exercise 1
            href: C:/jeffreylowps/ISSS624/In-class_Ex/In-class_Ex1/In-class_ex1.qmd
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

